services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80" # 외부의 80포트로 접속하면 Nginx가 받음
      - "443:443"
    environment:
      - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./NGINX/default.conf.template:/etc/nginx/templates/default.conf.template:ro # 설정 파일 연결
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: always

  app:
    build: ./BACKEND
    container_name: spring-backend
    ports:
      - "${SERVER_PORT}:8080"
    image: over4ction/harudang-app:latest
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - FRONT_DOMAIN=${FRONT_DOMAIN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - REFRESH_EXPIRATION=${REFRESH_EXPIRATION}
      - LANGSERVE_HOST=${LANGSERVE_HOST}
      - LANGSERVE_PORT=${LANGSERVE_PORT}
      - SPRING_PROFILES_ACTIVE=${ENV}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${PSQL_NAME}
      - SPRING_DATASOURCE_USERNAME=${PSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${PSQL_PW}
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      postgres:
        condition: service_started
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PW}
      POSTGRES_DB: ${PSQL_NAME}
    ports:
      - "${PSQL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: